### ISSUE TITLE
publication request

### ISSUE THREAD

**Issue by pmp-p** [TechnoVisual/Pygame-Zero#3]
Hi, as i'm currently porting pygame/pgzero to WebAssembly do you mind if your code gets published and integrated in the tech demo ?

https://pmp-p.github.io/pygame-wasm/

edit/ Thanks here they are !

https://pmp-p.github.io/pgzero-wasm/pygame.html?gh.lordmauve.pgzero

https://github.com/pygame/pygame/issues/718

**Comment by TechnoVisual** [comment]
Hi Paul - yes - no problem - thanks.
